/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AsyncRouteImport } from "./routes/async";
import { Route as ContextRouteImport } from "./routes/context";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PersistentRouteImport } from "./routes/persistent";
import { Route as SharedRouteImport } from "./routes/shared";
import { Route as TodoRouteImport } from "./routes/todo";

const TodoRoute = TodoRouteImport.update({
  id: "/todo",
  path: "/todo",
  getParentRoute: () => rootRouteImport,
} as any);
const SharedRoute = SharedRouteImport.update({
  id: "/shared",
  path: "/shared",
  getParentRoute: () => rootRouteImport,
} as any);
const PersistentRoute = PersistentRouteImport.update({
  id: "/persistent",
  path: "/persistent",
  getParentRoute: () => rootRouteImport,
} as any);
const ContextRoute = ContextRouteImport.update({
  id: "/context",
  path: "/context",
  getParentRoute: () => rootRouteImport,
} as any);
const AsyncRoute = AsyncRouteImport.update({
  id: "/async",
  path: "/async",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/async": typeof AsyncRoute;
  "/context": typeof ContextRoute;
  "/persistent": typeof PersistentRoute;
  "/shared": typeof SharedRoute;
  "/todo": typeof TodoRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/async": typeof AsyncRoute;
  "/context": typeof ContextRoute;
  "/persistent": typeof PersistentRoute;
  "/shared": typeof SharedRoute;
  "/todo": typeof TodoRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/async": typeof AsyncRoute;
  "/context": typeof ContextRoute;
  "/persistent": typeof PersistentRoute;
  "/shared": typeof SharedRoute;
  "/todo": typeof TodoRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/async" | "/context" | "/persistent" | "/shared" | "/todo";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/async" | "/context" | "/persistent" | "/shared" | "/todo";
  id:
    | "__root__"
    | "/"
    | "/async"
    | "/context"
    | "/persistent"
    | "/shared"
    | "/todo";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AsyncRoute: typeof AsyncRoute;
  ContextRoute: typeof ContextRoute;
  PersistentRoute: typeof PersistentRoute;
  SharedRoute: typeof SharedRoute;
  TodoRoute: typeof TodoRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/todo": {
      id: "/todo";
      path: "/todo";
      fullPath: "/todo";
      preLoaderRoute: typeof TodoRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/shared": {
      id: "/shared";
      path: "/shared";
      fullPath: "/shared";
      preLoaderRoute: typeof SharedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/persistent": {
      id: "/persistent";
      path: "/persistent";
      fullPath: "/persistent";
      preLoaderRoute: typeof PersistentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/context": {
      id: "/context";
      path: "/context";
      fullPath: "/context";
      preLoaderRoute: typeof ContextRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/async": {
      id: "/async";
      path: "/async";
      fullPath: "/async";
      preLoaderRoute: typeof AsyncRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsyncRoute: AsyncRoute,
  ContextRoute: ContextRoute,
  PersistentRoute: PersistentRoute,
  SharedRoute: SharedRoute,
  TodoRoute: TodoRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
